apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}-alertmanager-config
  labels:
    {{- include "rosa-federated-prometheus.labels" . | nindent 4 }}
    app.kubernetes.io/component: alertmanager
stringData:
  alertmanager.yaml: |
    {{ .Values.alertManager.configYaml | toYaml | nindent 4 }}
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}
spec:
  securityContext: {}
  replicas: 3
  configSecret: {{ include "rosa-federated-prometheus.fullname" . }}-alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}-alertmanager
  labels:
    {{- include "rosa-federated-prometheus.labels" . | nindent 4 }}
    app.kubernetes.io/app: alertmanager
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: {{ include "rosa-federated-prometheus.fullname" . }}
    app.kubernetes.io/name: alertmanager
