apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: {{ .Values.clusterName }}
stringData:
  autoImportRetry: "2"
  kubeconfig: |-
{{ .Files.Get .Values.kubeconfigPath | indent 4 -}}
type: Opaque

