apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: {{ .Values.cluster_name }}
stringData:
  autoImportRetry: "2"
  kubeconfig: |-
{{ .Files.Get "kubeconfig" | indent 4 }}
type: Opaque

