---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ecr-secret-operator.serviceAccountName" . }}-cluster-role
  labels:
    {{- include "ecr-secret-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - argohelmreposecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - argohelmreposecrets/finalizers
  verbs:
  - update
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - argohelmreposecrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - secrets/finalizers
  verbs:
  - update
- apiGroups:
  - ecr.mobb.redhat.com
  resources:
  - secrets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
