apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}
  labels:
    {{- include "rosa-federated-prometheus.labels" . | nindent 4 }}
spec:
  name: federated-prometheus.yaml
  datasources:
    - access: proxy
      editable: false
      isDefault: true
      basicAuth: true
      basicAuthPassword: "{{ .Values.prometheus.basicAuthPassword }}"
      basicAuthUser: "{{ .Values.prometheus.basicAuthUsername }}"
      jsonData:
        timeInterval: 5s
        tlsSkipVerify: true
      name: prometheus
      type: prometheus
      url: 'https://{{ include "rosa-federated-prometheus.fullname" . }}-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9091'