
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}-grafana
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rosa-federated-prometheus.fullname" . }}-grafana
subjects:
  - kind: ServiceAccount
    name: grafana-serviceaccount
    namespace: {{ .Release.Namespace }}
