apiVersion: v2
name: rosa-federated-prometheus
description: A Helm chart for Kubernetes

type: application

version: 0.1.1

appVersion: "0.1.0"

maintainers:
  - name: paulczar

home: https://github.com/rh-mobb/helm-charts
