---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.{{ include "rosa-federated-prometheus.fullname" . }}: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus-route"}}'
  name: {{ include "rosa-federated-prometheus.fullname" . }}
  labels:
    {{- include "rosa-federated-prometheus.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}
  labels:
    prometheus: {{ include "rosa-federated-prometheus.fullname" . }}
    {{- include "rosa-federated-prometheus.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  - services
  - endpoints
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "rosa-federated-prometheus.fullname" . }}
  labels:
    {{- include "rosa-federated-prometheus.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rosa-federated-prometheus.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "rosa-federated-prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
